from collections import defaultdict
from datetime import datetime, timedelta
from typing import List
from urllib.parse import urlparse

from flask import Flask, render_template


from forro_festivals.config import static_folder, root_path_flask, DateFormats
from forro_festivals.scripts.event import Event
from forro_festivals.scripts.db import get_events_from_db


def create_festivals_html(template='festivals.html'):
    events = get_events_from_db()

    cutoff = datetime.today() - timedelta(days=14)  # show some old festivals that recently happenend
    events = [event for event in events if event.validated and event.start > cutoff]

    festival_data = format_festival_data(events)

    app = Flask(__name__, root_path=root_path_flask)

    # The below 3 lines are needed since I added url_for into the base.html
    app.config['SERVER_NAME'] = 'localhost:5000'
    app.config['APPLICATION_ROOT'] = '/'
    app.config['PREFERRED_URL_SCHEME'] = 'http'


    with app.app_context():
        festivals = render_template(template, data=festival_data)

    static_folder.mkdir(exist_ok=True)
    with open(f'{static_folder}/{template}', 'w') as file:
        file.write(festivals)



def ensure_https_scheme(url: str):
    """prepends https if no scheme is contained in the url.
    Reason: for instance, if url is www.google.de the actual link
    that is generated by the html is www.forro-festivals.com/www.google.de
    or localhost:5000/www.google.de if running locally. This problem
    goes away if we use a full url."""
    parsed_url = urlparse(url)
    if not parsed_url.scheme:
        return f'https://{url}'
    elif parsed_url.scheme not in ['http', 'https']:
        # If the scheme is not http or https, prepend https://
        return f"https://{url}"
    else:
        # If the URL already has a valid scheme (http or https), return it as is
        return url

def format_festival_data(events: List[Event]):

    events = sorted(events, key=lambda event: event.start)

    year_month_events = defaultdict(list)
    for event in events:
        year_month = event.start.strftime('%B %Y')  # January 2025
        link = ensure_https_scheme(event.link)
        festival = {
            'location': f'{event.city}, {event.country}',
            'date_start': event.start.strftime(DateFormats.dm),
            'date_end': event.end.strftime(DateFormats.dm),
            'link': link,
            'link_text': event.link_text,
        }
        year_month_events[year_month].append(festival)

    return dict(year_month_events)



if __name__ == '__main__':
    create_festivals_html()
