name: reload forro-festivals.com

on:
  push:
    branches:
      - master

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: deploy forro-festivals.com
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               www.forro-festivals.com/reload-bash?api_token=${{ secrets.API_TOKEN }}
