name: reload forro_festivals-festivals.com

on:
  push:
    branches:
      - master

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      #- name: deploy forro-festivals.com
      #  run: |
      #    curl -X POST \
      #         -H "Content-Type: application/json" \
      #         www.forro-festivals.com/reload-app?api_token=${{ secrets.API_TOKEN }}
      - name: deploy forro-festivals.com 2
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               www.forro-festivals.com/reload-bash
