name: reload forro-festivals.com

on:
  push:
    branches:
      - master

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: deploy forro-festivals.com
        run: |
          curl -v -X POST --fail \
               -H "Content-Type: application/json" \
               -H "Authorization: Token ${{ secrets.API_TOKEN }}" \
               www.forro-festivals.com/reload-bash
