name: reload forro-festivals.com

on:
  push:
    branches:
      - master

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: deploy forro-festivals.com
        run: |
          # Login
          curl -v -X POST --fail \
            -c cookies.txt \
            -d "id=${{ secrets.RELOAD_USER }}" \
            -d "password=${{ secrets.PASSWORD_RELOAD_USER }}" \
            https://www.forro-festivals.com/login
          
          # Use cookies to authenticate
          curl -v -X POST --fail \
           -b cookies.txt
           -H "Content-Type: application/json" \
           https://www.forro-festivals.com/reload-bash

          rm cookies.txt