name: reload forro_festivals-festivals.com

on:
  push:
    branches:
      - master

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is a test message"
      - name: Send POST request to external service
        run: |
          curl -X POST \
               -H "Content-Type: application/json" \
               www.forro-festivals.com/git-webkook?auth_token=${{ secrets.API_TOKEN }}
